// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://gitlab.paradeum.com/pld/cloud-batch",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "post Auth",
                "parameters": [
                    {
                        "description": "auth",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Auth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    }
                }
            }
        },
        "/auth/passwd": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Update password",
                "parameters": [
                    {
                        "description": "updateAuth",
                        "name": "updateAuth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateAuth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "401": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    }
                }
            }
        },
        "/batch/servers": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Batch Create Servers",
                "parameters": [
                    {
                        "description": "batchCreateServers",
                        "name": "batchCreateServers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BatchCreateServersForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Batch Get Servers",
                "parameters": [
                    {
                        "description": "batchDeleteServersForm",
                        "name": "batchDeleteServersForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BatchDeleteServersForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    }
                }
            }
        },
        "/servers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Batch Get Servers",
                "parameters": [
                    {
                        "enum": [
                            "bfs",
                            "dfs",
                            "test"
                        ],
                        "type": "string",
                        "description": "project",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "aliyun"
                        ],
                        "type": "string",
                        "description": "provider",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "running",
                            "deploying",
                            "starting",
                            "deploy_fail",
                            "unknown"
                        ],
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "batch_number",
                        "name": "batch_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Get Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.ResponseString"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ResponseString": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "errDetail": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                }
            }
        },
        "models.Auth": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5
                }
            }
        },
        "models.BatchCreateServersForm": {
            "type": "object",
            "required": [
                "count",
                "cpu_core_count",
                "memory_size_mb",
                "project",
                "provider",
                "region_scope"
            ],
            "properties": {
                "count": {
                    "description": "创建数量",
                    "type": "integer",
                    "default": 1,
                    "enum": [
                        1,
                        2,
                        5,
                        10,
                        20,
                        50,
                        100
                    ]
                },
                "cpu_core_count": {
                    "description": "cpu 核数",
                    "type": "integer",
                    "default": 4,
                    "enum": [
                        1,
                        2,
                        4,
                        8,
                        16
                    ]
                },
                "memory_size_mb": {
                    "description": "内存（单位 M)",
                    "type": "integer",
                    "default": 8192,
                    "enum": [
                        512,
                        1024,
                        2048,
                        4096,
                        8192,
                        16384
                    ]
                },
                "project": {
                    "description": "项目标签",
                    "type": "string",
                    "default": "bfs",
                    "enum": [
                        "bfs",
                        "dfs"
                    ]
                },
                "provider": {
                    "description": "云提供者",
                    "type": "string",
                    "default": "aliyun",
                    "enum": [
                        "aliyun"
                    ]
                },
                "region_scope": {
                    "description": "区域前缀: all 全部, cnml 中国大陆, cn 中国， ap 亚太， us 美洲， eu 欧洲, me 中东",
                    "type": "string",
                    "default": "cnml",
                    "enum": [
                        "all",
                        "cnml",
                        "cn",
                        "us",
                        "ap",
                        "me",
                        "eu"
                    ]
                }
            }
        },
        "models.BatchDeleteServersForm": {
            "type": "object",
            "properties": {
                "batch_number": {
                    "description": "创建主机的批号",
                    "type": "string",
                    "maxLength": 14,
                    "minLength": 14
                },
                "ids": {
                    "description": "主机 ids, 如果设置了 ids, 忽略其它参数",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "project": {
                    "description": "项目标签",
                    "type": "string",
                    "default": "test",
                    "enum": [
                        "bfs",
                        "dfs",
                        "test"
                    ]
                },
                "provider": {
                    "description": "云提供者",
                    "type": "string",
                    "default": "aliyun",
                    "enum": [
                        "aliyun"
                    ]
                },
                "region_scope": {
                    "description": "区域前缀: all 全部, cnml 中国大陆, cn 中国， ap 亚太， us 美洲， eu 欧洲, me 中东",
                    "type": "string",
                    "default": "cnml",
                    "enum": [
                        "all",
                        "cnml",
                        "cn",
                        "us",
                        "ap",
                        "me",
                        "eu"
                    ]
                }
            }
        },
        "models.UpdateAuth": {
            "type": "object",
            "required": [
                "oldPassword",
                "password",
                "username"
            ],
            "properties": {
                "oldPassword": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "v0.0.3",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Cloud Batch API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
